### ISSUE TITLE
Required `namespace` parameter not implemented for Momento

### ISSUE THREAD

**Issue by kvcache** [momentohq/simple-spring-memcached#3]
Per discussion on https://github.com/momentohq/simple-spring-memcached/pull/2

The namespace parameter doesn't actually namespace instantiations of the cache. If you have 2 methods you want to cache, and you give them different namespaces so they don't collide - _**they will collide anyway**_.

**Comment by tylerburdsall** [comment]
Turns out this is in fact implemented. Ellery's demo demonstrates this: https://github.com/momentohq/java-ssm-momento-demo

If you run the demo and then check your momento cache with key: `$namespace:$givenKey`, you'll find that it is in fact prepending the keys for us:

```
Tylers-MacBook-Pro :: ~ » momento cache get --name test --key "default:foo"
[2022-03-02T23:49:23Z INFO  momento::commands::cache::cache] getting key: default:foo from cache: test
1 foo
Tylers-MacBook-Pro :: ~ »
```
